# -*- coding: utf-8 -*-
"""model122108729.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/JazzLiberal/DataMining/blob/main/model122108729.ipynb
"""

import pandas as pd
import numpy as np
from sklearn import model_selection
from sklearn import preprocessing
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV


#Define a new Pipeline using the RandomForest Classifier 
pipe = Pipeline([('scaler', MinMaxScaler()), ('pca', PCA()), ('rf', RandomForestClassifier())])


#update parameter grid for new random forest and pca arguments
param_grid = {'pca__n_components': [24],
              'pca__whiten' : [True],
              'rf__max_features': [0.3],
              'rf__max_depth': [None],
              'rf__min_samples_leaf' : [2],
              'rf__n_estimators': [9]}


#Define and fit the grid as before, trialled different cross validations
grid = GridSearchCV(pipe, param_grid, cv=8)
grid.fit(train_features, train_labels)

print("Best score: ", grid.best_score_)

y_pred = grid.best_estimator_.predict(test_features)

# Compute the accuracy score of the model
accuracy = accuracy_score(test_labels, y_pred)
print("Accuracy score: ", accuracy)